disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - line_length
  - empty_enum_arguments
  - identifier_name
  - force_cast

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
